name: textlint
on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install dependencies
        run: npm install

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Fetch base branch
        run: git fetch origin main

      - name: Run textlint
        run: |
          git diff origin/main HEAD --diff-filter=AM --name-only | grep \.md$ > changed_files.txt
          cat changed_files.txt | xargs npx textlint

      - name: Run reviewdog
        if: ${{ failure() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat changed_files.txt \
          | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review
